import { defineConfig } from 'astro/config';

export default defineConfig({
  // 用户站点（仓库名 = lllygkj33-creator.github.io），站点在根路径，不需要 base
  site: 'https://lllygkj33-creator.github.io',
  // 目录重构前的旧地址，全部转到新地址（部署在 Pages 上是 meta refresh 形式的跳转）
  redirects: {
    '/content-quality/example-001/': '/content-quality/examples/001-media-server-hardware/',
    '/content-quality/example-002/': '/content-quality/examples/002-capcut-ai-avatar-ads/',
    '/method/basics/skyscraper-content-opt/': '/skyscraper/',
    '/seo/content/skyscraper/': '/skyscraper/',
    '/geo/on-page/ai-citation-tracking-guide/': '/geo/measurement/ai-citation-tracking-guide/',
    '/geo/on-page/ai-crawler-access-guidelines/': '/geo/machine/ai-crawler-access-guidelines/',
    '/geo/on-page/ai-referral-traffic-analysis/': '/geo/measurement/ai-referral-traffic-analysis/',
    '/geo/on-page/author-identity-expert-reviewer/': '/geo/entities/author-identity-expert-reviewer/',
    '/geo/on-page/brand-entity-consistency-guidelines/': '/geo/entities/brand-entity-consistency-guidelines/',
    '/geo/on-page/citation-friendly-paragraph-guidelines/': '/geo/answers/citation-friendly-paragraph-guidelines/',
    '/geo/on-page/claim-evidence-boundary-guidelines/': '/geo/answers/claim-evidence-boundary-guidelines/',
    '/geo/on-page/consensus-cross-validation-guidelines/': '/geo/entities/consensus-cross-validation-guidelines/',
    '/geo/on-page/direct-answer-guidelines/': '/geo/answers/direct-answer-guidelines/',
    '/geo/on-page/entity-disambiguation-guidelines/': '/geo/entities/entity-disambiguation-guidelines/',
    '/geo/on-page/entity-relationship-graph/': '/geo/entities/entity-relationship-graph/',
    '/geo/on-page/geo-content-freshness-versioning/': '/geo/machine/geo-content-freshness-versioning/',
    '/geo/on-page/geo-performance-metrics/': '/geo/measurement/geo-performance-metrics/',
    '/geo/on-page/geo-prompt-set-testing-guidelines/': '/geo/measurement/geo-prompt-set-testing-guidelines/',
    '/geo/on-page/geo-title-decision-tree/': '/geo/basics/geo-title-decision-tree/',
    '/geo/on-page/hreflang-cross-language-geo/': '/geo/machine/hreflang-cross-language-geo/',
    '/geo/on-page/information-density/': '/geo/basics/information-density/',
    '/geo/on-page/information-provenance-guidelines/': '/geo/entities/information-provenance-guidelines/',
    '/geo/on-page/llms-txt/': '/geo/machine/llms-txt/',
    '/geo/on-page/machine-friendly-content-format/': '/geo/machine/machine-friendly-content-format/',
    '/geo/on-page/mention-rate-citation-rate-guide/': '/geo/measurement/mention-rate-citation-rate-guide/',
    '/geo/on-page/multimodal-geo-guidelines/': '/geo/answers/multimodal-geo-guidelines/',
    '/geo/on-page/passage-chunk-structure-guidelines/': '/geo/answers/passage-chunk-structure-guidelines/',
    '/geo/on-page/query-fan-out-principles/': '/geo/basics/query-fan-out-principles/',
    '/geo/on-page/sameas-external-identity-guidelines/': '/geo/entities/sameas-external-identity-guidelines/',
    '/geo/on-page/source-evidence-levels-guidelines/': '/geo/entities/source-evidence-levels-guidelines/',
    '/geo/on-page/structured-data-schema-for-geo/': '/geo/machine/structured-data-schema-for-geo/',
    '/geo/on-page/table-structured-answer-guidelines/': '/geo/answers/table-structured-answer-guidelines/',
    '/geo/on-page/time-version-entity-relations-guidelines/': '/geo/entities/time-version-entity-relations-guidelines/',
    '/geo/on-page/wikidata-geo-guide/': '/geo/entities/wikidata-geo-guide/',
    '/geo/on-page/wikipedia-geo-guide/': '/geo/entities/wikipedia-geo-guide/',
    '/google-algorithm/basics/google-bert-guide/': '/google-algorithm/semantics/google-bert-guide/',
    '/google-algorithm/basics/google-eeat-guide/': '/google-algorithm/quality/google-eeat-guide/',
    '/google-algorithm/basics/google-freshness-qdf-guide/': '/google-algorithm/signals/google-freshness-qdf-guide/',
    '/google-algorithm/basics/google-helpful-content-hcu-guide/': '/google-algorithm/quality/google-helpful-content-hcu-guide/',
    '/google-algorithm/basics/google-hummingbird-algorithm-history/': '/google-algorithm/semantics/google-hummingbird-algorithm-history/',
    '/google-algorithm/basics/google-mum-guide/': '/google-algorithm/semantics/google-mum-guide/',
    '/google-algorithm/basics/google-neural-matching-guide/': '/google-algorithm/semantics/google-neural-matching-guide/',
    '/google-algorithm/basics/google-pagerank-guide/': '/google-algorithm/links/google-pagerank-guide/',
    '/google-algorithm/basics/google-panda-algorithm-history/': '/google-algorithm/quality/google-panda-algorithm-history/',
    '/google-algorithm/basics/google-penguin-algorithm-history/': '/google-algorithm/links/google-penguin-algorithm-history/',
    '/google-algorithm/basics/google-rankbrain-guide/': '/google-algorithm/semantics/google-rankbrain-guide/',
    '/google-algorithm/basics/google-search-algorithm-history/': '/google-algorithm/overview/google-search-algorithm-history/',
    '/google-algorithm/basics/google-serp-exploration-feedback-model/': '/google-algorithm/signals/google-serp-exploration-feedback-model/',
    '/google-algorithm/basics/google-ymyl-guide/': '/google-algorithm/quality/google-ymyl-guide/',
    '/google-algorithm/basics/navboost-user-interaction-signals/': '/google-algorithm/signals/navboost-user-interaction-signals/',
    '/seo/basics/brand-nonbrand-seo-analysis/': '/seo/analytics/brand-nonbrand-seo-analysis/',
    '/seo/basics/content-freshness-update-guidelines/': '/seo/content/content-freshness-update-guidelines/',
    '/seo/basics/faq-query-coverage-guidelines/': '/seo/content/faq-query-coverage-guidelines/',
    '/seo/basics/ga4-organic-search-analysis/': '/seo/analytics/ga4-organic-search-analysis/',
    '/seo/basics/gsc-metrics-guide/': '/seo/analytics/gsc-metrics-guide/',
    '/seo/basics/image-seo-guidelines/': '/seo/content/image-seo-guidelines/',
    '/seo/basics/keyword-cannibalization-guide/': '/seo/content/keyword-cannibalization-guide/',
    '/seo/basics/page-indexing-troubleshooting/': '/seo/technical/page-indexing-troubleshooting/',
    '/seo/basics/page-template-duplicate-content-guidelines/': '/seo/content/page-template-duplicate-content-guidelines/',
    '/seo/basics/ranking-drop-diagnostic-tree/': '/seo/analytics/ranking-drop-diagnostic-tree/',
    '/seo/basics/seo-experiment-redesign-validation/': '/seo/analytics/seo-experiment-redesign-validation/',
    '/seo/basics/seo-page-growth-decay-analysis/': '/seo/analytics/seo-page-growth-decay-analysis/',
    '/seo/basics/seo-weekly-performance-analysis/': '/seo/analytics/seo-weekly-performance-analysis/',
    '/seo/basics/serp-competition-analysis-guidelines/': '/seo/analytics/serp-competition-analysis-guidelines/',
    '/seo/off-page/backlink-types-anchor-text-guidelines/': '/seo/links/backlink-types-anchor-text-guidelines/',
    '/seo/off-page/pr-press-release-guidelines/': '/seo/links/pr-press-release-guidelines/',
    '/seo/on-page/canonical-guide/': '/seo/technical/canonical-guide/',
    '/seo/on-page/information-gain/': '/seo/content/information-gain/',
    '/seo/on-page/robots-txt-guide/': '/seo/technical/robots-txt-guide/',
    '/seo/tech/404-soft-404-guidelines/': '/seo/technical/404-soft-404-guidelines/',
    '/seo/tech/core-web-vitals-guide/': '/seo/technical/core-web-vitals-guide/',
    '/seo/tech/crawl-budget-guide/': '/seo/technical/crawl-budget-guide/',
    '/seo/tech/hreflang-multilingual-seo-guide/': '/seo/technical/hreflang-multilingual-seo-guide/',
    '/seo/tech/javascript-seo-rendering-guide/': '/seo/technical/javascript-seo-rendering-guide/',
    '/seo/tech/orphan-page-seo-guide/': '/seo/technical/orphan-page-seo-guide/',
    '/seo/tech/redirect-301-302-guidelines/': '/seo/technical/redirect-301-302-guidelines/',
    '/seo/tech/sitemap-xml-guide/': '/seo/technical/sitemap-xml-guide/',
    '/seo/tech/structured-data-schema-basics/': '/seo/technical/structured-data-schema-basics/',
  },
  markdown: {
    // 和参考站一样：浅色模式浅色代码块，深色模式深色代码块
    shikiConfig: { themes: { light: 'github-light-default', dark: 'github-dark' } },
  },
});
